[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SageTea Edge"
authors = [{name = "Rúben Carneiro", email = "rubencarneiro01@gmail.com"}]
dynamic = ["version", "description"]
